/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tela.Cadastros;

import Entidades.Produto;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.HibernateUtil;
import tela.Relatorios.ListarProdutos;

/**
 *
 * @author felip
 */
public class CadastroProdutos extends javax.swing.JDialog {

    private Boolean habilitarEdicao = false;
    private Produto prod = new Produto();
    private List<Produto> listaProdutos = new ArrayList<>();
    private JFrame frame;

    public JButton getBtIrLista() {
        return btIrLista;
    }

    public void setBtIrLista(JButton btIrLista) {
        this.btIrLista = btIrLista;
    }

    public Boolean getHabilitarEdicao() {
        return habilitarEdicao;
    }

    public void setHabilitarEdicao(Boolean habilitarEdicao) {
        this.habilitarEdicao = habilitarEdicao;
    }

    public CadastroProdutos(JFrame frame) {
        this.frame = frame;
    }

    public void limpaCampos() {
        campoTipo.setText("");
        campoNCM.setText("");
        campoEstoque.setText("");
        campoCor.setText("");
        campoNumeração.setText("");
        campoValorVenda.setText("");
    }

    public void SetCampos(Produto prod) {
        campoTipo.setText(prod.getTipo());
        campoNumeração.setText(prod.getNumeracao());
        campoCor.setText(prod.getCor());
        campoNCM.setText(prod.getNcm());
        campoValorVenda.setText(prod.getValorUnitarioVenda().toString());
        campoEstoque.setText(prod.getEstoque().toString());
        this.prod.setId(prod.getId());

        validaCampos("novo");

    }

    public boolean adicionarProd(Produto prod) {
        if (prod.getTipo() == null || prod.getTipo().isEmpty()
                || prod.getNcm() == null || prod.getNcm().isEmpty()
                || prod.getEstoque() == null
                || prod.getCor() == null || prod.getCor().isEmpty()
                || prod.getNumeracao() == null || prod.getNumeracao().isEmpty()
                || prod.getValorUnitarioVenda() == null) {
            JOptionPane.showMessageDialog(null, "TODOS OS CAMPOS PRECISAM SER PREENCHIDOS");
            return false;
        }
        return true;
    }

    public void validaCampos(String operacao) {
        if (operacao.equals("inicio")) {
            btNovo.setEnabled(true);
            btSalvar.setEnabled(false);
            btCancelar.setEnabled(false);
            campoTipo.setEnabled(false);
            campoCor.setEnabled(false);
            campoEstoque.setEnabled(false);
            campoNCM.setEnabled(false);
            campoNumeração.setEnabled(false);
            campoValorVenda.setEnabled(false);
        } else if (operacao.equals("novo")) {
            btNovo.setEnabled(false);
            btSalvar.setEnabled(true);
            btCancelar.setEnabled(true);
            campoTipo.setEnabled(true);
            campoCor.setEnabled(true);
            campoEstoque.setEnabled(true);
            campoNCM.setEnabled(true);
            campoNumeração.setEnabled(true);
            campoValorVenda.setEnabled(true);
        } else if (operacao.equals("selecionado")) {
            btNovo.setEnabled(true);
            btSalvar.setEnabled(false);
            btCancelar.setEnabled(true);
            campoTipo.setEnabled(false);
            campoCor.setEnabled(false);
            campoEstoque.setEnabled(false);
            campoNCM.setEnabled(false);
            campoNumeração.setEnabled(false);
            campoValorVenda.setEnabled(false);
        }

    }

    public CadastroProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        validaCampos("inicio");
        limpaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSalvar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        campoValorVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btNovo = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoTipo = new javax.swing.JTextField();
        campoNumeração = new javax.swing.JTextField();
        campoCor = new javax.swing.JTextField();
        campoNCM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoEstoque = new javax.swing.JTextField();
        btIrLista = new javax.swing.JButton();
        btsair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btSalvar.setText("SALVAR");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jLabel10.setText("PreçoVenda");

        campoValorVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorVendaActionPerformed(evt);
            }
        });
        campoValorVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoValorVendaKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Cadastro de Produto");

        btNovo.setText("NOVO");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btCancelar.setText("CANCELAR");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo:");

        jLabel5.setText("Numeração:");

        jLabel6.setText("Cor:");

        jLabel7.setText("NCM:");

        campoNumeração.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeraçãoActionPerformed(evt);
            }
        });

        campoNCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNCMActionPerformed(evt);
            }
        });

        jLabel8.setText("Estoque:");

        campoEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEstoqueActionPerformed(evt);
            }
        });

        btIrLista.setText("LISTA DE PRODUTOS");
        btIrLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIrListaActionPerformed(evt);
            }
        });

        btsair.setText("SAIR");
        btsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoNumeração, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoCor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campoNCM, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(campoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btIrLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btsair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoNumeração, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoNCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btNovo)
                    .addComponent(btCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIrLista)
                    .addComponent(btsair))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        prod.setTipo(campoTipo.getText());
        prod.setNumeracao(campoNumeração.getText());
        prod.setCor(campoCor.getText());
        prod.setNcm(campoNCM.getText());
        prod.setCont(0d);
        String precoTextoVenda = campoValorVenda.getText();
        if (!precoTextoVenda.equals("")) {
            double precovendaDouble = Double.parseDouble(precoTextoVenda);
            BigDecimal salarioBigDecimal = new BigDecimal(precovendaDouble);
            prod.setValorUnitarioVenda(salarioBigDecimal);
        }

        prod.setEstoque(Double.parseDouble(campoEstoque.getText()));

        if (adicionarProd(prod)) {
            HibernateUtil.beginTransaction();
            HibernateUtil.getSession().merge(prod);
            HibernateUtil.commitTransaction();
            HibernateUtil.closeSession();
            if (habilitarEdicao) {
                JOptionPane.showMessageDialog(null, "EDIÇÃO REALIZADA COM SUCESSO");
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "PRODUTO CADASTRADO COM SUCESSO");
            }
            limpaCampos();
            habilitarEdicao = false;
            prod = new Produto();
            validaCampos("inicio");
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void campoValorVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorVendaActionPerformed

    }//GEN-LAST:event_campoValorVendaActionPerformed

    private void campoValorVendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoValorVendaKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_campoValorVendaKeyTyped

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        prod = new Produto();
        limpaCampos();
        validaCampos("novo");
    }//GEN-LAST:event_btNovoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        limpaCampos();
        habilitarEdicao = false;
        validaCampos("inicio");
    }//GEN-LAST:event_btCancelarActionPerformed

    private void campoNumeraçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeraçãoActionPerformed

    }//GEN-LAST:event_campoNumeraçãoActionPerformed

    private void campoNCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNCMActionPerformed

    private void campoEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEstoqueActionPerformed

    }//GEN-LAST:event_campoEstoqueActionPerformed

    private void btIrListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIrListaActionPerformed
        habilitarEdicao = false;
        dispose();
        ListarProdutos frm = new ListarProdutos(frame, true);
        frm.setVisible(true);
    }//GEN-LAST:event_btIrListaActionPerformed

    private void btsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsairActionPerformed
        dispose();

    }//GEN-LAST:event_btsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="prodlapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroProdutos dialog = new CadastroProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btIrLista;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btsair;
    private javax.swing.JTextField campoCor;
    private javax.swing.JTextField campoEstoque;
    private javax.swing.JTextField campoNCM;
    private javax.swing.JTextField campoNumeração;
    private javax.swing.JTextField campoTipo;
    private javax.swing.JTextField campoValorVenda;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
